baseurl = "/"
languageCode = "en-us"
title = "Cash Flow Challenge"
theme = "hugo-theme-casper"
disqusShortname = "cash-flow-challenge"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-107046289-2"
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "100 Games, 100 Properties, 1 Crazy New Life"
  cover = "images/cover.jpg"
  author = "Bill A"
  authorlocation = "Virginia"
  authorwebsite = "https://billa.com"
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-107046289-2"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..."
  githubName = "vjeantet"
  twitterName = "vjeantet"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "your_twitter"
